.TH Encrip Encript
.SH NAME
Encrip -e [archivo]
.SH SYNOPSIS
.B Encripta archivos, codigos usando la cifrado por desplazamiento, código de César o desplazamiento de César con un step 4 por defecto 
.SH DESCRIPTION
Recibe la bandera "e" ó "d" para realizar el encriptado mientras que la bandera "s" y "a" es opcional y es a continuacion.
Mientras que la bandera "z" es para ejecutar un archivo encriptado previamente
.B -e esta opción será utilizada para cifrar.

.B -d esta opción será utilizada para descifrar.

.B -s esta opción permite utilizar un desplazamiento distinto al predeterminado (45).

.B -a esta opción permite utilizar un alfabeto distinto al predeterminado (ASCII imprimible).

.SH AUTHOR
Gallardo Tinoco Andrés Amadeus
